language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.1.5
before_script:
  - dotnet restore
script:  
  - dotnet test ./TravelCardsSortingTest/TravelCardsSortingTest -c Release -f netcoreapp2.0