language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.1.300-preview1-0081747
before_script:
  - dotnet restore
script:  
  - dotnet test ./TravelCardsSortingTest -c Release -f netcoreapp2.0